title: Philipp Guldimann
description: AI & Platform Engineer — from data to AI that creates value in production.
logo: /assets/img/headshot_circle.jpeg
show_downloads: false
theme: jekyll-theme-minimal
